# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import isthiskeanureeves.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.STAR_RATINGS_RATING_MODEL),
        ('isthiskeanureeves', '0002_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to=isthiskeanureeves.models.user_upload)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isthiskeanureeves.Category')),
                ('ratings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.STAR_RATINGS_RATING_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
